name: Update Data and Deploy Streamlit App

on:
  schedule:
    - cron: '0 18 * * *' # Runs at 12 AM IST every day
  workflow_dispatch: # Trigger workflow manually

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main # or specify your branch name
          
      - name: Set up Git
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Specify the version of Python you need
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # if you have any dependencies
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
